spring.application.name=reservahotelera
spring.datasource.url=jdbc:oracle:thin:@r3otlzvdm9gnlibe_high?TNS_ADMIN=${user.dir}/Wallet_UGNFM3WC8EM1NFQI
spring.datasource.username=${DB_USERNAME:CHAVEZ}
spring.datasource.password=ClaseFS123456-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
