spring.application.name=reservahotelera
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@ugnfm3wc8em1nfqi_high
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${WALLET_PATH:${user.dir}/Wallet_UGNFM3WC8EM1NFQI}
spring.datasource.username=${DB_USERNAME:CHAVEZ}
spring.datasource.password=ClaseFS123456-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
logging.level.root=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO
